### PR TITLE
Fix broken build when using rust 1.37.0 support 

### LINKED ISSUE #236: cargo-apk install builds debug build
Additionally, the install command needs to support the release flag.

### PR DESCRIPTION
**Pull request by philip-alldredge**
Build using cargo-apk and rust 1.37.0 results in a binary which does not export `ANativeActivity_onCreate`. Seems related to https://github.com/rust-lang/rust/issues/62088.

This fixes that issue and also switches to using cdylib. The cdylib switch is not necessary for the fix but it is more correct and reduces file sizes.

This also resolves #236 by supporting the debug flag in the install command and automatically builds with release. This is in line with `cargo install` behavior and it is in line with the behavior described when using `--help`.

Should resolve #236, #235 and parts of #234.

### CODE REVIEW

File: cargo-apk/injected-glue/lib.rs [hunk 1]
```diff
@@ -641,3 +641,23 @@ pub fn load_asset(filename: &str) -> Result<Vec<u8>, AssetError> {
     };
     Ok(vec)
 }
+
+// Exported function which is called be Android's NativeActivity
+#[no_mangle]
+#[inline(never)]
+pub unsafe extern "C" fn ANativeActivity_onCreate(
```
Comment (mb64) [inline cargo-apk/injected-glue/lib.rs]: `pub` and `#[inline(never)]` don't do anything here – Rust visibility has no impact on the visibility of the symbols in the final binary.

File: cargo-apk/native_app_glue/android_native_app_glue.c [hunk 2]
```diff
@@ -420,8 +420,10 @@ static void onInputQueueDestroyed(ANativeActivity* activity, AInputQueue* queue)
     android_app_set_input((struct android_app*)activity->instance, NULL);
 }
 
+// Renamed to ANativeActivity_onCreate2 to allow injected-glue to define ANativeActivity_onCreate which will
+// will be exported and will call this function.
 JNIEXPORT
-void ANativeActivity_onCreate(ANativeActivity* activity, void* savedState,
+void ANativeActivity_onCreate2(ANativeActivity* activity, void* savedState,
```
Comment (mb64) [inline cargo-apk/native_app_glue/android_native_app_glue.c]: I would prefer a more explanatory name than `ANativeActivity_onCreate2` – maybe something like `native_app_glue_onCreate`?

Also, due to rustc's version script, JNIEXPORT don't do anything here.  (It expands to `__attribute__((visibility("default")))`, which is supposed to make it a global symbol in the presence of `-fvisibility=hidden`, but gets overridden by the version script.)

**Comment by philip-alldredge** [comment]
@mb64  pushed changes.

**Comment by mb64** [comment]
Great! LGTM – merging.
